trigger:
  branches:
    include:
      - refs/heads/master
      - refs/tags/release-*
  paths:
    include:
      - iiot-platform
      - .pipelines/devops/ci-iiot-platform.yml 

pr: none

variables:
  vmImageName: 'ubuntu-latest'
  zmqImageRepository: 'iiotfactoryconnectivity050zmq'
  zmqWorkingDirectory: 'iiot-platform/iiot.factory.connectivity050.zmq'

stages:
  - stage: dev
    displayName: 'DEV - Build and Push docker images'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    variables:
        - template: ../variables/dev.yml
        - group: dev_env_secrets
    jobs:
    - template: ../templates/iiot-platform/template-ci-iiot-platform.yml
      parameters:
        containerRegistry: $(containerRegistry)
        servicePrincipalId: $(servicePrincipalId)
        servicePrincipalSecret: $(servicePrincipalSecret)
        zmqImageRepository: $(zmqImageRepository)
        zmqWorkingDirectory: $(zmqWorkingDirectory)

  - stage: qa
    displayName: 'QA - Build and Push docker images'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-')
    variables:
        - template: ../variables/qa.yml
        - group: qa_env_secrets
    jobs:
    - template: ../templates/iiot-platform/template-ci-iiot-platform.yml
      parameters:
        containerRegistry: $(containerRegistry)
        servicePrincipalId: $(servicePrincipalId)
        servicePrincipalSecret: $(servicePrincipalSecret)
        zmqImageRepository: $(zmqImageRepository)
        zmqWorkingDirectory: $(zmqWorkingDirectory)
  
