trigger:
  branches:
    include:
      - refs/heads/master
      - refs/tags/release-*
  paths:
    include:
      - iiot-platform
      - .pipelines/devops/ci-iiot-platform.yml 

pr: none

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: dev
    displayName: 'DEV - Build and Push docker image'
    #condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    variables:
        - template: ../variables/dev.yml
        - group: dev_env_secrets
    jobs:
    - template: ../templates/template-ci-iiot-platform.yml
      parameters:
        tenantId: $(tenantId)
        containerRegistry: $(containerRegistry)
        servicePrincipalId: $(servicePrincipalId)
        servicePrincipalSecret: $(servicePrincipalSecret)
        zmqImageRepository: 'iiotfactoryconnectivity050zmq'
        zmqWorkingDirectory: 'iiot-platform/iiot.factory.connectivity050.zmq'

  - stage: qa
    displayName: 'QA - Build and Push docker image'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/release-')
    variables:
        - template: ../variables/qa.yml
        - group: qa_env_secrets
    jobs:
    - template: ../templates/template-ci-iiot-platform.yml
      parameters:
        tenantId: $(tenantId)
        containerRegistry: $(containerRegistry)
        servicePrincipalId: $(servicePrincipalId)
        servicePrincipalSecret: $(servicePrincipalSecret)
        zmqImageRepository: 'iiotfactoryconnectivity050zmq'
        zmqWorkingDirectory: 'iiot-platform/iiot.factory.connectivity050.zmq'
  
