parameters:
  - name: containerRegistry
    type: string
  - name: servicePrincipalId
    type: string
  - name: servicePrincipalSecret
    type: string
  - name: workingDirectory
    type: string

steps:
  - bash: |
      echo "Login using service principal ${{ parameters.servicePrincipalId }}"
      docker login ${{ parameters.containerRegistry }}.azurecr.io -u ${{ parameters.servicePrincipalId }} -p=$SP_SECRET
    displayName: Login to docker
    workingDirectory: ${{ parameters.workingDirectory }}
    env:
      SP_SECRET: ${{ parameters.servicePrincipalSecret }}