parameters:
  - name: imageName
    type: string
  - name: workingDirectory
    type: string

steps:
  - bash: |
           echo "Build image: ${{parameters.imageName}}"
           docker push ${{parameters.imageName}}
    displayName: Publishing docker image
    workingDirectory: ${{ parameters.workingDirectory }}