parameters:
  - name: containerRegistry
    type: string
  - name: servicePrincipalId
    type: string
  - name: servicePrincipalSecret
    type: string
  - name: zmqImageRepository
    type: string
  - name: zmqWorkingDirectory
    type: string

jobs:
    - job: build_and_push_zmq_docker_image
      displayName: Zmq Adapter
      pool:
        vmImage: $(vmImageName)
      steps:
      - template: ../templates/template-build-and-push-docker-image.yml
        parameters:
          containerRegistry: ${{ containerRegistry }}
          servicePrincipalId: ${{ servicePrincipalId }}
          servicePrincipalSecret: ${{ servicePrincipalSecret }}
          imageRepository: ${{ zmqImageRepository }}
          workingDirectory: ${{ zmqWorkingDirectory }}