parameters:
  - name: containerRegistry
    type: string
  - name: servicePrincipalId
    type: string
  - name: servicePrincipalSecret
    type: string
  - name: zmqImageRepository
    type: string
  - name: zmqDockerfilePath
    type: string

jobs:
    - job: build_and_push_zmq_docker_image
      displayName: Build and Push Zmq Docker image
      pool:
        vmImage: $(vmImageName) # Sprawdzimy czy działa
      steps:
      - task: Bash@3
        displayName: Login to ACR
        inputs:
          targetType: 'inline'
          script: 
            echo "Login using service principal ${{ parameters.servicePrincipalId }}"
            docker version
            docker login `${{ parameters.containerRegistry }}.azurecr.io` -u ${{ parameters.servicePrincipalId }} -p=$SP_SECRET
        env:
          SP_SECRET: ${{ parameters.servicePrincipalSecret }}
      - task: Bash@3
        displayName: Build and push zmq image
        inputs:
          targetType: 'inline'
          script: 
            imageName=${{ parameters.containerRegistry }}.azurecr.io/${{ parameters.zmqImageRepository }}:$(Build.BuildId)
            echo "Build and push $imageName"
            docker build -f ${{parameters.zmqDockerfilePath}} -t $(Build.BuildId) .
            docker push $imageName
      # - task: Docker@2
      #   displayName: Build and push app image to container registry
      #   inputs:
      #     command: buildAndPush
      #     repository: ${{ parameters.zmqImageRepository }}
      #     dockerfile: ${{ parameters.zmqDockerfilePath }}
      #     containerRegistry: ${{ parameters.containerRegistry }}
      #     tags: |
      #       $(Build.BuildId)