parameters:
  - name: tenantId
    type: string
  - name: containerRegistry
    type: string
  - name: servicePrincipalId
    type: string
  - name: servicePrincipalSecret
    type: string
  - name: zmqImageRepository
    type: string
  - name: zmqWorkingDirectory
    type: string

jobs:
    - job: build_and_push_zmq_docker_image
      displayName: Build and Push Zmq Docker image
      pool:
        vmImage: $(vmImageName) # Sprawdzimy czy działa
      steps:
      - bash: |
         az login --service-principal -u ${{ parameters.servicePrincipalId }} -p=$SP_SECRET --tenant ${{ parameters.tenantId }}
         az acr login --name ${{ parameters.containerRegistry }}
         
         imageName=${{ parameters.containerRegistry }}.azurecr.io/${{ parameters.zmqImageRepository }}:$(Build.BuildId)
         echo "Build and push $imageName"
         docker build -f `${{parameters.zmqWorkingDirectory}}/Dockerfile' -t $(Build.BuildId) .
         docker push $imageName

        displayName: Build and publish docker image
        workingDirectory: ${{ parameters.zmqWorkingDirectory }}
        env:
          SP_SECRET: ${{ parameters.servicePrincipalSecret }}
          
      # - task: Docker@2
      #   displayName: Build and push app image to container registry
      #   inputs:
      #     command: buildAndPush
      #     repository: ${{ parameters.zmqImageRepository }}
      #     dockerfile: ${{ parameters.zmqDockerfilePath }}
      #     containerRegistry: ${{ parameters.containerRegistry }}
      #     tags: |
      #       $(Build.BuildId)