parameters:
  - name: containerRegistry
    type: string
  - name: servicePrincipalId
    type: string
  - name: servicePrincipalSecret
    type: string
  - name: zmqImageRepository
    type: string
  - name: zmqWorkingDirectory
    type: string

jobs:
- template: ../../templates/iiot-platform/template-zmq-adapter.yml
  parameters:
    containerRegistry: ${{ parameters.containerRegistry }}
    servicePrincipalId: ${{ parameters.servicePrincipalId }}
    servicePrincipalSecret: ${{ parameters.servicePrincipalSecret }}
    imageRepository: ${{ parameters.zmqImageRepository }}
    workingDirectory: ${{ parameters.zmqWorkingDirectory }}
    dockerFileName: 'Dockerfile'